create database cfd;

INSERT INTO users(id, avatar_url, birthday, created_date, email, fullname, gender, is_active, password, phone, updated_date, username, version, role_id)
VALUES
    ('quockhanh123', 'index.png', '2004-02-01', '2023-01-10', 'quockhanh123@example.com', 'Quốc Khánh', 'MALE', 1, 'password123', '0901234567', '2023-01-15', 'quockhanh', 1, 3),
    ('user001', 'avatar1.png', '1990-05-12', '2023-01-10', 'user001@example.com', 'Nguyễn Văn A', 'MALE', 1, 'password123', '0901123456', '2023-01-15', 'user001', 1, 1),
    ('user002', 'avatar2.png', '1985-09-23', '2023-02-20', 'user002@example.com', 'Trần Thị B', 'FEMALE', 1, 'password456', '0902234567', '2023-02-25', 'user002', 1, 2),
    ('user003', 'avatar3.png', '1992-11-07', '2023-03-05', 'user003@example.com', 'Lê Văn C', 'PRIVATE', 1, 'password789', '0903345678', '2023-03-10', 'user003', 1, 1),
    ('user004', 'avatar4.png', '1996-06-15', '2023-04-12', 'user004@example.com', 'Phạm Thị D', 'FEMALE', 1, 'passwordabc', '0904456789', '2023-04-18', 'user004', 1, 2),
    ('user005', 'avatar5.png', '2001-01-25', '2023-05-10', 'user005@example.com', 'Hoàng Văn E', 'MALE', 1, 'passworddef', '0905567890', '2023-05-15', 'user005', 1, 1),
    ('user006', 'avatar6.png', '1999-04-30', '2023-06-08', 'user006@example.com', 'Lý Thị F', 'FEMALE', 1, 'passwordghi', '0906678901', '2023-06-13', 'user006', 1, 2),
    ('user007', 'avatar7.png', '1988-03-11', '2023-07-07', 'user007@example.com', 'Ngô Văn G', 'MALE', 1, 'passwordjkl', '0907789012', '2023-07-12', 'user007', 1, 1),
    ('user008', 'avatar8.png', '1995-10-21', '2023-08-15', 'user008@example.com', 'Đặng Thị H', 'FEMALE', 1, 'passwordmno', '0908890123', '2023-08-20', 'user008', 1, 2),
    ('user009', 'avatar9.png', '2003-12-19', '2023-09-14', 'user009@example.com', 'Vũ Văn I', 'PRIVATE', 1, 'passwordpqr', '0909901234', '2023-09-18', 'user009', 1, 1);

INSERT INTO categories (category_name)
VALUES
    ('Programming'),
    ('Data Science'),
    ('Web Development'),
    ('Cloud Computing'),
    ('Cybersecurity'),
    ('Mobile Development'),
    ('AI and Robotics'),
    ('Blockchain'),
    ('Digital Marketing'),
    ('Game Development'),
    ('Machine Learning'),
    ('Graphic Design'),
    ('Ethical Hacking'),
    ('Big Data'),
    ('Content Writing'),
    ('Python Programming'),
    ('SEO'),
    ('Data Analysis'),
    ('Product Management'),
    ('UI/UX Design');


INSERT INTO courses (category_id, cover_image, created_at, description, level, price, title, updated_at, instructor_id, is_published)
VALUES
    (3, 'cover1.jpg', '2024-01-10', 'Khóa học lập trình Java cơ bản', 'Beginner', 1500000, 'Java Cơ Bản', '2024-01-15', 'user001', 0),
    (7, 'cover2.jpg', '2024-01-12', 'Khóa học phát triển Web với HTML và CSS', 'Beginner', 1200000, 'HTML & CSS Cơ Bản', '2024-01-16', 'user001', 0),
    (2, 'cover3.jpg', '2024-02-01', 'Khóa học Python cơ bản cho người mới bắt đầu', 'Beginner', 1800000, 'Python Cơ Bản', '2024-02-05', 'user003', 0),
    (10, 'cover4.jpg', '2024-02-10', 'Khóa học SQL và quản trị cơ sở dữ liệu', 'Intermediate', 2500000, 'SQL & Database', '2024-02-15', 'user001', 0),
    (5, 'cover5.jpg', '2024-03-03', 'Khóa học phát triển ứng dụng Android với Kotlin', 'Intermediate', 3000000, 'Android với Kotlin', '2024-03-08', 'user003', 0),
    (1, 'cover6.jpg', '2024-03-15', 'Khóa học phân tích và thiết kế phần mềm', 'Advanced', 2700000, 'Phân Tích & Thiết Kế', '2024-03-20', 'user001', 0),
    (6, 'cover7.jpg', '2024-04-01', 'Khóa học ReactJS và phát triển Frontend', 'Intermediate', 3200000, 'ReactJS Cơ Bản', '2024-04-05', 'user003', 0),
    (8, 'cover8.jpg', '2024-04-15', 'Khóa học NodeJS và phát triển Backend', 'Advanced', 3300000, 'NodeJS Cơ Bản', '2024-04-20', 'user001', 0),
    (4, 'cover9.jpg', '2024-05-01', 'Khóa học bảo mật ứng dụng web', 'Advanced', 3500000, 'Bảo Mật Web', '2024-05-05', 'user003', 0),
    (1, 'cover10.jpg', '2024-05-10', 'Khóa học Java nâng cao', 'Advanced', 2500000, 'Java Nâng Cao', '2024-06-05', 'user001', 0),
    (7, 'cover11.jpg', '2024-06-10', 'Khóa học thiết kế giao diện web', 'Intermediate', 2000000, 'Thiết Kế Web', '2024-06-15', 'user001', 0),
    (5, 'cover12.jpg', '2024-06-20', 'Khóa học trí tuệ nhân tạo với Python', 'Advanced', 4500000, 'AI với Python', '2024-06-25', 'user003', 0),
    (10, 'cover13.jpg', '2024-07-01', 'Khóa học phát triển game với Unity', 'Intermediate', 2800000, 'Phát Triển Game', '2024-07-05', 'user001', 0),
    (3, 'cover14.jpg', '2024-07-15', 'Khóa học lập trình C# cơ bản', 'Beginner', 1500000, 'C# Cơ Bản', '2024-07-20', 'user003', 0),
    (2, 'cover15.jpg', '2024-08-01', 'Khóa học khoa học dữ liệu với R', 'Intermediate', 3000000, 'Data Science với R', '2024-08-05', 'user001', 0),
    (9, 'cover16.jpg', '2024-08-15', 'Khóa học lập trình mạng với Python', 'Advanced', 4000000, 'Lập Trình Mạng', '2024-08-20', 'user001', 0),
    (6, 'cover17.jpg', '2024-09-01', 'Khóa học DevOps cho doanh nghiệp', 'Advanced', 3500000, 'DevOps', '2024-09-05', 'user001', 0),
    (4, 'cover18.jpg', '2024-09-10', 'Khóa học Flutter cơ bản cho ứng dụng mobile', 'Beginner', 2000000, 'Flutter Cơ Bản', '2024-09-15', 'user003', 0),
    (8, 'cover19.jpg', '2024-09-20', 'Khóa học tối ưu hóa SEO cho website', 'Intermediate', 2200000, 'SEO Web', '2024-09-25', 'user001', 0),
    (1, 'cover20.jpg', '2024-10-01', 'Khóa học JavaScript cơ bản', 'Beginner', 1600000, 'JavaScript Cơ Bản', '2024-10-05', 'user001', 0),
    (5, 'cover21.jpg', '2024-10-10', 'Khóa học PHP và MySQL', 'Intermediate', 1900000, 'PHP & MySQL', '2024-10-15', 'user003', 0),
    (3, 'cover22.jpg', '2024-10-20', 'Khóa học phát triển ứng dụng web với Django', 'Advanced', 2400000, 'Django Web', '2024-10-25', 'user001', 0),
    (9, 'cover23.jpg', '2024-10-30', 'Khóa học học máy với Python', 'Advanced', 3600000, 'Machine Learning', '2024-11-05', 'user001', 0),
    (2, 'cover24.jpg', '2024-11-01', 'Khóa học React Native cho di động', 'Intermediate', 3100000, 'React Native', '2024-11-05', 'user003', 0),
    (4, 'cover25.jpg', '2024-11-10', 'Khóa học phát triển game với Unreal Engine', 'Intermediate', 2300000, 'Unreal Engine', '2024-11-15', 'user001', 0),
    (6, 'cover26.jpg', '2024-11-15', 'Khóa học kỹ năng mềm cho lập trình viên', 'Beginner', 1400000, 'Kỹ Năng Mềm', '2024-11-20', 'user001', 0),
    (8, 'cover27.jpg', '2024-11-20', 'Khóa học kiểm thử phần mềm', 'Intermediate', 2000000, 'Kiểm Thử Phần Mềm', '2024-11-25', 'user001', 0),
    (10, 'cover28.jpg', '2024-11-30', 'Khóa học UX/UI Design', 'Advanced', 2800000, 'UX/UI Design', '2024-12-05', 'user003', 0),
    (1, 'cover29.jpg', '2024-12-01', 'Khóa học an ninh mạng', 'Advanced', 3000000, 'An Ninh Mạng', '2024-12-05', 'user001', 0);

INSERT INTO sections (title, course_id)
VALUES
    ('Giới thiệu về Java', 31),
    ('Cài đặt môi trường Java', 31),
    ('Cú pháp cơ bản của Java', 31),
    ('Lập trình hướng đối tượng trong Java', 31),
    ('Xử lý ngoại lệ trong Java', 31),
    ('Giới thiệu về HTML', 32),
    ('Cấu trúc cơ bản của một trang HTML', 32),
    ('CSS cơ bản', 32),
    ('Responsive Design với CSS', 32),
    ('Giới thiệu về Python', 33),
    ('Biến và kiểu dữ liệu trong Python', 33),
    ('Câu lệnh điều kiện trong Python', 33),
    ('Vòng lặp trong Python', 33),
    ('Hàm trong Python', 33),
    ('Giới thiệu về SQL', 34),
    ('Câu lệnh SELECT', 34),
    ('Câu lệnh INSERT', 34),
    ('Câu lệnh UPDATE', 34),
    ('Câu lệnh DELETE', 34),
    ('Giới thiệu về lập trình Android', 35),
    ('Cài đặt Android Studio', 35),
    ('Lập trình với Kotlin', 35),
    ('Giao diện người dùng trong Android', 35),
    ('Xử lý dữ liệu trong Android', 35),
    ('Khái niệm thiết kế phần mềm', 36),
    ('Các mô hình thiết kế phần mềm', 36),
    ('Phân tích yêu cầu', 36),
    ('Thiết kế cơ sở dữ liệu', 36),
    ('Tài liệu thiết kế', 36),
    ('Giới thiệu về ReactJS', 37),
    ('State và Props trong ReactJS', 37),
    ('Lifecycle trong ReactJS', 37),
    ('Quản lý trạng thái với Redux', 37),
    ('Tương tác với API', 37),
    ('Giới thiệu về NodeJS', 38),
    ('Xây dựng API với NodeJS', 38),
    ('Quản lý người dùng', 38),
    ('Xử lý tệp trong NodeJS', 38),
    ('Triển khai ứng dụng NodeJS', 38),
    ('Giới thiệu về bảo mật web', 39),
    ('Xác thực và phân quyền', 39),
    ('Nguyên tắc bảo mật', 39),
    ('Kiểm thử bảo mật', 39),
    ('Bảo mật thông tin', 39),
    ('Giới thiệu về lập trình C#', 40),
    ('Các kiểu dữ liệu trong C#', 40),
    ('Lập trình hướng đối tượng trong C#', 40),
    ('Xử lý lỗi trong C#', 40),
    ('Xây dựng ứng dụng với C#', 40),
    ('Giới thiệu về JavaScript', 41),
    ('Các cấu trúc dữ liệu trong JavaScript', 41),
    ('Các phương thức trong JavaScript', 41),
    ('Quản lý sự kiện trong JavaScript', 41),
    ('Thư viện và Frameworks JavaScript', 41),
    ('Giới thiệu về Machine Learning', 42),
    ('Giới thiệu về TensorFlow', 42),
    ('Xử lý dữ liệu với Python', 42),
    ('Xây dựng mô hình Machine Learning', 42),
    ('Đánh giá mô hình', 42),
    ('Giới thiệu về thiết kế giao diện', 43),
    ('Nguyên tắc thiết kế giao diện người dùng', 43),
    ('Thiết kế với Adobe XD', 43),
    ('Thiết kế responsive', 43),
    ('Nguyên tắc UX', 43);

INSERT INTO lectures (created_at, title, type, updated_at, section_id)
VALUES
    (NOW(), 'Giới thiệu về Java', 'video', NOW(), 65),
    (NOW(), 'Cài đặt môi trường Java', 'video', NOW(), 65),
    (NOW(), 'Cú pháp cơ bản của Java', 'video', NOW(), 65),
    (NOW(), 'Lập trình hướng đối tượng trong Java', 'video', NOW(), 65),
    (NOW(), 'Xử lý ngoại lệ trong Java', 'video', NOW(), 65),
    (NOW(), 'Giới thiệu về HTML', 'video', NOW(), 66),
    (NOW(), 'Cấu trúc cơ bản của một trang HTML', 'video', NOW(), 66),
    (NOW(), 'CSS cơ bản', 'video', NOW(), 66),
    (NOW(), 'Responsive Design với CSS', 'video', NOW(), 66),
    (NOW(), 'Giới thiệu về Python', 'video', NOW(), 67),
    (NOW(), 'Biến và kiểu dữ liệu trong Python', 'video', NOW(), 67),
    (NOW(), 'Câu lệnh điều kiện trong Python', 'video', NOW(), 67),
    (NOW(), 'Vòng lặp trong Python', 'video', NOW(), 67),
    (NOW(), 'Hàm trong Python', 'video', NOW(), 67),
    (NOW(), 'Giới thiệu về SQL', 'video', NOW(), 68),
    (NOW(), 'Câu lệnh SELECT', 'video', NOW(), 68),
    (NOW(), 'Câu lệnh INSERT', 'video', NOW(), 68),
    (NOW(), 'Câu lệnh UPDATE', 'video', NOW(), 68),
    (NOW(), 'Câu lệnh DELETE', 'video', NOW(), 68),
    (NOW(), 'Giới thiệu về lập trình Android', 'video', NOW(), 69),
    (NOW(), 'Cài đặt Android Studio', 'video', NOW(), 69),
    (NOW(), 'Lập trình với Kotlin', 'video', NOW(), 69),
    (NOW(), 'Giao diện người dùng trong Android', 'video', NOW(), 69),
    (NOW(), 'Xử lý dữ liệu trong Android', 'video', NOW(), 69),
    (NOW(), 'Khái niệm thiết kế phần mềm', 'video', NOW(), 70),
    (NOW(), 'Các mô hình thiết kế phần mềm', 'video', NOW(), 70),
    (NOW(), 'Phân tích yêu cầu', 'video', NOW(), 70),
    (NOW(), 'Thiết kế cơ sở dữ liệu', 'video', NOW(), 70),
    (NOW(), 'Tài liệu thiết kế', 'video', NOW(), 70),
    (NOW(), 'Giới thiệu về ReactJS', 'video', NOW(), 71),
    (NOW(), 'State và Props trong ReactJS', 'video', NOW(), 71),
    (NOW(), 'Lifecycle trong ReactJS', 'video', NOW(), 71),
    (NOW(), 'Quản lý trạng thái với Redux', 'video', NOW(), 71),
    (NOW(), 'Tương tác với API', 'video', NOW(), 71),
    (NOW(), 'Giới thiệu về NodeJS', 'video', NOW(), 72),
    (NOW(), 'Xây dựng API với NodeJS', 'video', NOW(), 72),
    (NOW(), 'Quản lý người dùng', 'video', NOW(), 72),
    (NOW(), 'Xử lý tệp trong NodeJS', 'video', NOW(), 72),
    (NOW(), 'Triển khai ứng dụng NodeJS', 'video', NOW(), 72),
    (NOW(), 'Giới thiệu về bảo mật web', 'video', NOW(), 73),
    (NOW(), 'Xác thực và phân quyền', 'video', NOW(), 73),
    (NOW(), 'Nguyên tắc bảo mật', 'video', NOW(), 73),
    (NOW(), 'Kiểm thử bảo mật', 'video', NOW(), 73),
    (NOW(), 'Bảo mật thông tin', 'video', NOW(), 73),
    (NOW(), 'Giới thiệu về lập trình C#', 'video', NOW(), 74),
    (NOW(), 'Các kiểu dữ liệu trong C#', 'video', NOW(), 74),
    (NOW(), 'Lập trình hướng đối tượng trong C#', 'video', NOW(), 74),
    (NOW(), 'Xử lý lỗi trong C#', 'video', NOW(), 74),
    (NOW(), 'Xây dựng ứng dụng với C#', 'video', NOW(), 74),
    (NOW(), 'Giới thiệu về JavaScript', 'video', NOW(), 75),
    (NOW(), 'Các cấu trúc dữ liệu trong JavaScript', 'video', NOW(), 75),
    (NOW(), 'Các phương thức trong JavaScript', 'video', NOW(), 75),
    (NOW(), 'Quản lý sự kiện trong JavaScript', 'video', NOW(), 75),
    (NOW(), 'Thư viện và Frameworks JavaScript', 'video', NOW(), 75),
    (NOW(), 'Giới thiệu về Machine Learning', 'video', NOW(), 76),
    (NOW(), 'Giới thiệu về TensorFlow', 'video', NOW(), 76),
    (NOW(), 'Xử lý dữ liệu với Python', 'video', NOW(), 76),
    (NOW(), 'Xây dựng mô hình Machine Learning', 'video', NOW(), 76),
    (NOW(), 'Đánh giá mô hình', 'video', NOW(), 76),
    (NOW(), 'Giới thiệu về thiết kế giao diện', 'video', NOW(), 77),
    (NOW(), 'Nguyên tắc thiết kế giao diện người dùng', 'video', NOW(), 77),
    (NOW(), 'Thiết kế với Adobe XD', 'video', NOW(), 77),
    (NOW(), 'Thiết kế responsive', 'video', NOW(), 77),
    (NOW(), 'Nguyên tắc UX', 'video', NOW(), 77),
    (NOW(), 'Giới thiệu về công nghệ AI', 'video', NOW(), 78),
    (NOW(), 'Các ứng dụng của AI', 'video', NOW(), 78),
    (NOW(), 'Học máy cơ bản', 'video', NOW(), 78),
    (NOW(), 'Deep Learning là gì?', 'video', NOW(), 78),
    (NOW(), 'Giới thiệu về UX/UI', 'video', NOW(), 79),
    (NOW(), 'Thực hành thiết kế giao diện', 'video', NOW(), 79),
    (NOW(), 'Nghiên cứu người dùng', 'video', NOW(), 79),
    (NOW(), 'Tối ưu hóa trải nghiệm người dùng', 'video', NOW(), 79),
    (NOW(), 'Giới thiệu về dữ liệu lớn', 'video', NOW(), 80),
    (NOW(), 'Phân tích dữ liệu lớn', 'video', NOW(), 80),
    (NOW(), 'Xử lý dữ liệu không cấu trúc', 'video', NOW(), 80),
    (NOW(), 'Công cụ trong dữ liệu lớn', 'video', NOW(), 80),
    (NOW(), 'Giới thiệu về lập trình web', 'video', NOW(), 81),
    (NOW(), 'Xây dựng trang web với HTML/CSS', 'video', NOW(), 81),
    (NOW(), 'Lập trình front-end với JavaScript', 'video', NOW(), 81),
    (NOW(), 'Lập trình back-end với Node.js', 'video', NOW(), 81),
    (NOW(), 'Giới thiệu về điện toán đám mây', 'video', NOW(), 82),
    (NOW(), 'Các dịch vụ đám mây phổ biến', 'video', NOW(), 82),
    (NOW(), 'Triển khai ứng dụng trên đám mây', 'video', NOW(), 82),
    (NOW(), 'Bảo mật trong đám mây', 'video', NOW(), 82),
    (NOW(), 'Giới thiệu về phát triển ứng dụng di động', 'video', NOW(), 83),
    (NOW(), 'Lập trình ứng dụng Android', 'video', NOW(), 83),
    (NOW(), 'Lập trình ứng dụng iOS', 'video', NOW(), 83),
    (NOW(), 'Xây dựng ứng dụng đa nền tảng', 'video', NOW(), 83),
    (NOW(), 'Giới thiệu về DevOps', 'video', NOW(), 84),
    (NOW(), 'Công cụ DevOps phổ biến', 'video', NOW(), 84),
    (NOW(), 'Triển khai CI/CD', 'video', NOW(), 84),
    (NOW(), 'Quản lý cấu hình', 'video', NOW(), 84),
    (NOW(), 'Giới thiệu về Blockchain', 'video', NOW(), 85),
    (NOW(), 'Ứng dụng Blockchain trong kinh doanh', 'video', NOW(), 85),
    (NOW(), 'Smart Contracts là gì?', 'video', NOW(), 85),
    (NOW(), 'Xây dựng ứng dụng Blockchain', 'video', NOW(), 85),
    (NOW(), 'Giới thiệu về Internet of Things (IoT)', 'video', NOW(), 86),
    (NOW(), 'Ứng dụng IoT trong cuộc sống', 'video', NOW(), 86),
    (NOW(), 'Công nghệ cảm biến', 'video', NOW(), 86),
    (NOW(), 'Bảo mật trong IoT', 'video', NOW(), 86);

INSERT INTO comments (comment_text, created_at, star, updated_at, comment_id, courses_id, lecture_id, user_id)
VALUES
    ('Tuyệt vời! Mình học được nhiều điều.', NOW(), 0, NOW(), NULL, NULL, 65, 'user001'),
    ('Rất hữu ích, cảm ơn giảng viên!', NOW(), 0, NOW(), NULL, NULL, 66, 'user001'),
    ('Chất lượng video không tốt lắm.', NOW(), 0, NOW(), NULL, NULL, 67, 'user003'),
    ('Nội dung rất chi tiết và dễ hiểu.', NOW(), 0, NOW(), NULL, NULL, 68, 'user003'),
    ('Mong có thêm nhiều bài học như thế này.', NOW(), 0, NOW(), NULL, NULL, 69, 'user005'),
    ('Thời gian học hơi dài.', NOW(), 0, NOW(), NULL, NULL, 70, 'user005'),
    ('Mình gặp khó khăn với bài này.', NOW(), 0, NOW(), NULL, NULL, 71, 'user007'),
    ('Giảng viên rất nhiệt tình.', NOW(), 0, NOW(), NULL, NULL, 72, 'user007'),
    ('Bài học này quá dễ.', NOW(), 0, NOW(), NULL, NULL, 73, 'user001'),
    ('Mình yêu thích cách giảng dạy!', NOW(), 0, NOW(), NULL, NULL, 74, 'user001'),
    ('Mong chờ bài tiếp theo.', NOW(), 0, NOW(), NULL, NULL, 75, 'user003'),
    ('Mình chưa hiểu rõ lắm.', NOW(), 0, NOW(), NULL, NULL, 76, 'user003'),
    ('Có thể giải thích rõ hơn không?', NOW(), 0, NOW(), NULL, NULL, 77, 'user005'),
    ('Tuyệt vời, cảm ơn giảng viên!', NOW(), 0, NOW(), NULL, NULL, 78, 'user005'),
    ('Nội dung cần cập nhật.', NOW(), 0, NOW(), NULL, NULL, 79, 'user007'),
    ('Mình rất thích khóa học này.', NOW(), 0, NOW(), NULL, NULL, 80, 'user007'),
    ('Rất hay, mình sẽ giới thiệu cho bạn bè.', NOW(), 0, NOW(), NULL, NULL, 81, 'user001'),
    ('Khó quá, mình không theo kịp.', NOW(), 0, NOW(), NULL, NULL, 82, 'user001'),
    ('Phần này rất dễ hiểu.', NOW(), 0, NOW(), NULL, NULL, 83, 'user003'),
    ('Cảm ơn giảng viên đã chia sẻ!', NOW(), 0, NOW(), NULL, NULL, 84, 'user003'),
    ('Có thể thêm ví dụ thực tế không?', NOW(), 0, NOW(), NULL, NULL, 65, 'user005'),
    ('Đây là bài học mình yêu thích nhất.', NOW(), 0, NOW(), NULL, NULL, 66, 'user005'),
    ('Rất khó để thực hành.', NOW(), 0, NOW(), NULL, NULL, 67, 'user007'),
    ('Phần này nên được giảng dạy kỹ hơn.', NOW(), 0, NOW(), NULL, NULL, 68, 'user007'),
    ('Khóa học rất tuyệt!', NOW(), 0, NOW(), NULL, NULL, 69, 'user001'),
    ('Mình học được nhiều kỹ năng.', NOW(), 0, NOW(), NULL, NULL, 70, 'user001'),
    ('Có thể cung cấp tài liệu tham khảo không?', NOW(), 0, NOW(), NULL, NULL, 71, 'user003'),
    ('Rất đáng để học.', NOW(), 0, NOW(), NULL, NULL, 72, 'user003'),
    ('Nên cải thiện âm thanh.', NOW(), 0, NOW(), NULL, NULL, 73, 'user005'),
    ('Bài học này thật sự có giá trị.', NOW(), 0, NOW(), NULL, NULL, 74, 'user005'),
    ('Cảm ơn vì những thông tin bổ ích.', NOW(), 0, NOW(), NULL, NULL, 75, 'user007'),
    ('Mình muốn có thêm bài học về thực hành.', NOW(), 0, NOW(), NULL, NULL, 76, 'user007'),
    ('Phần lý thuyết hơi nhiều.', NOW(), 0, NOW(), NULL, NULL, 77, 'user001'),
    ('Mong chờ video tiếp theo!', NOW(), 0, NOW(), NULL, NULL, 78, 'user001'),
    ('Video này quá ngắn.', NOW(), 0, NOW(), NULL, NULL, 79, 'user003'),
    ('Nội dung bài học rất thú vị.', NOW(), 0, NOW(), NULL, NULL, 80, 'user003'),
    ('Mình muốn tham gia lớp học này.', NOW(), 0, NOW(), NULL, NULL, 81, 'user005'),
    ('Nên có thêm phần câu hỏi.', NOW(), 0, NOW(), NULL, NULL, 82, 'user005'),
    ('Khóa học này không thú vị.', NOW(), 0, NOW(), NULL, NULL, 83, 'user007'),
    ('Rất dễ hiểu, mình thích bài này.', NOW(), 0, NOW(), NULL, NULL, 84, 'user007'),
    ('Bài học nên có thêm phần thực hành.', NOW(), 0, NOW(), NULL, NULL, 65, 'user001'),
    ('Mong được học nhiều hơn nữa.', NOW(), 0, NOW(), NULL, NULL, 66, 'user001'),
    ('Video này thật sự có giá trị.', NOW(), 0, NOW(), NULL, NULL, 67, 'user003'),
    ('Cảm ơn vì đã tạo ra khóa học này.', NOW(), 0, NOW(), NULL, NULL, 68, 'user003'),
    ('Nên có thêm phần bài tập.', NOW(), 0, NOW(), NULL, NULL, 69, 'user005'),
    ('Khóa học này rất bổ ích.', NOW(), 0, NOW(), NULL, NULL, 70, 'user005'),
    ('Tôi thấy nó rất thú vị.', NOW(), 0, NOW(), NULL, NULL, 71, 'user007'),
    ('Cảm ơn vì bài học chất lượng!', NOW(), 0, NOW(), NULL, NULL, 72, 'user007'),
    ('Rất cần thêm tài liệu tham khảo.', NOW(), 0, NOW(), NULL, NULL, 73, 'user001'),
    ('Mong có thêm video về phần này.', NOW(), 0, NOW(), NULL, NULL, 74, 'user001'),
    ('Khóa học rất thú vị.', NOW(), 0, NOW(), NULL, NULL, 75, 'user003'),
    ('Rất dễ hiểu và rõ ràng.', NOW(), 0, NOW(), NULL, NULL, 76, 'user003'),
    ('Tôi đã gặp một số khó khăn.', NOW(), 0, NOW(), NULL, NULL, 77, 'user005'),
    ('Bài này hơi khó.', NOW(), 0, NOW(), NULL, NULL, 78, 'user005'),
    ('Rất tuyệt vời!', NOW(), 0, NOW(), NULL, NULL, 79, 'user007'),
    ('Cần nhiều ví dụ thực tiễn hơn.', NOW(), 0, NOW(), NULL, NULL, 80, 'user007'),
    ('Tôi rất hài lòng với bài học.', NOW(), 0, NOW(), NULL, NULL, 81, 'user001'),
    ('Cảm ơn vì những thông tin hữu ích.', NOW(), 0, NOW(), NULL, NULL, 82, 'user001'),
    ('Khóa học này là một lựa chọn tốt.', NOW(), 0, NOW(), NULL, NULL, 83, 'user003'),
    ('Mong có thêm nhiều khóa học như vậy.', NOW(), 0, NOW(), NULL, NULL, 84, 'user003'),
    ('Nội dung hơi khó.', NOW(), 0, NOW(), NULL, NULL, 65, 'user005'),
    ('Rất dễ hiểu, mình thích bài này.', NOW(), 0, NOW(), NULL, NULL, 66, 'user005'),
    ('Bài học nên có thêm phần thực hành.', NOW(), 0, NOW(), NULL, NULL, 67, 'user007'),
    ('Mong được học nhiều hơn nữa.', NOW(), 0, NOW(), NULL, NULL, 68, 'user007'),
    ('Video này thật sự có giá trị.', NOW(), 0, NOW(), NULL, NULL, 69, 'user001'),
    ('Cảm ơn vì đã tạo ra khóa học này.', NOW(), 0, NOW(), NULL, NULL, 70, 'user001'),
    ('Nên có thêm phần bài tập.', NOW(), 0, NOW(), NULL, NULL, 71, 'user003'),
    ('Khóa học này rất bổ ích.', NOW(), 0, NOW(), NULL, NULL, 72, 'user003'),
    ('Tôi thấy nó rất thú vị.', NOW(), 0, NOW(), NULL, NULL, 73, 'user005'),
    ('Cảm ơn vì bài học chất lượng!', NOW(), 0, NOW(), NULL, NULL, 74, 'user005'),
    ('Rất cần thêm tài liệu tham khảo.', NOW(), 0, NOW(), NULL, NULL, 75, 'user007'),
    ('Mong có thêm video về phần này.', NOW(), 0, NOW(), NULL, NULL, 76, 'user007'),
    ('Khóa học rất thú vị.', NOW(), 0, NOW(), NULL, NULL, 77, 'user001'),
    ('Rất dễ hiểu và rõ ràng.', NOW(), 0, NOW(), NULL, NULL, 78, 'user001'),
    ('Tôi đã gặp một số khó khăn.', NOW(), 0, NOW(), NULL, NULL, 79, 'user003'),
    ('Bài này hơi khó.', NOW(), 0, NOW(), NULL, NULL, 80, 'user003'),
    ('Rất tuyệt vời!', NOW(), 0, NOW(), NULL, NULL, 81, 'user005'),
    ('Cần nhiều ví dụ thực tiễn hơn.', NOW(), 0, NOW(), NULL, NULL, 82, 'user005'),
    ('Tôi rất hài lòng với bài học.', NOW(), 0, NOW(), NULL, NULL, 83, 'user007'),
    ('Cảm ơn vì những thông tin hữu ích.', NOW(), 0, NOW(), NULL, NULL, 84, 'user007');


select
    c.id as id,
    u.id as idUserComment,
    u.fullname as fullName,
    u.avatar_url as profilePicture,
    c.comment_text as commentText,
    userCommentParent.fullname as nameUserReply,
    c.comment_id as parentId
from comments c
inner join users u on c.user_id = u.id
left join comments commentParent on c.comment_id = commentParent.id
left join users userCommentParent on commentParent.user_id = userCommentParent.id